### ISSUE TITLE
reorganize the server

### ISSUE THREAD

**Issue by the-wulf** [the-wulf/thewulf-webapp#1]
# proposed re-organization of server
### some current characteristics

`Ubuntu 12.04 LTS`
`memory: 16gb total`
`swap: 3gb total`
`cpus: 8 total`
`harddrive: 3.6tb total (1.7tb used)`
### some quick cleanups
- build software in ~/build or in ~/tmp - for ease of cleanup after software has been built
- serve django apps from ~/webapps/{production,development}/{app,assets}
- separate virtualenvs for different projects contained within app directory
  - i.e. `~/envs/production` contains the python environment for production while `~/webapps/<project_name>/env/development` contains the python requirements for development
- clean up static files (compress js, css, on build to server ... eventually add to VCS)
- install python and pip into `~/opt/`
- add virtualenvs to the correct directory, i.e. in the root of the domain -> `~/dev.thewulf.org/<!env!>`

**Comment by andrewyoung1991** [comment]
cd ~/tmp
wget http://www.python.org/ftp/python/2.7.7/Python-2.7.7.tgz
tar zxvf Python-2.7.7.tgz
cd Python-2.7.7
./configure --prefix=$HOME/opt/python-2.7.7
make
make install

**Comment by andrewyoung1991** [comment]
following the dreamhost guide:
- projects are in the user home directory and a folder named after the domain
- virtualenvs are in the domain named directory along side `tmp/restart.txt` and `passenger_wsgi.py`
  ! the `passenger_wsgi.py` file is a wsgi file, instead it adds the virtualenv and the django settings file to $PATH
